export const ROUTES = {
  ENTRY: "/",
  ONBOARDING: "/onboarding",
  LOGIN: "/login",
  HOME: "/home",
  CAPTURE: "/capture",
  CAPTURE_PRODUCTS: "/capture/products",
  ANALYSIS_LOADING: "/analysis/loading",
  REPORT: "/report/:analysisId",
  ROUTINE: "/routine",
  ROUTINE_MORNING: "/routine/morning",
  ROUTINE_EVENING: "/routine/evening",
  ROUTINE_MORNING_DETAIL: "/routine/morning/:routineId",
  ROUTINE_EVENING_DETAIL: "/routine/evening/:routineId",
  HISTORY: "/history",
  MYPAGE: "/mypage",
  PURCHASE_COMPARE: "/purchase/compare",
  PURCHASE_RESULT: "/purchase/result",
  KAKAO_CALLBACK: "/login/kakao/callback",
  NOT_FOUND: "/not-found",
};